let games = [  
    {
        id: 1,
        name: "Sekiro: Shadow Die Twice",
        image: "\images//sekiroSmall.png",
        imageLarge: "\images//sekiroLarge.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 2 days ago",
        checkpointImage: "\images//noidea.png",
        checkpointName: "Shinobi Bengining...",
        date: "12/22",
        time: "08:14 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "All Ninjutsu Techniques",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Man Without Equal",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 2,
        name: "Red Dead Redemption 2",
        image: "\images//rdrSmall.png",
        imageLarge: "\images//rdrBig.png",
        bgCover: "\images//rdrBG.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 12 hours ago",
        checkpointImage: "\images//rdrCheckPoint.png",
        checkpointName: "Where's Johnny?!",
        date: "12/22",
        time: "03:55 AM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Thrid Time Lucky",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Legend of the West",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 3,
        image: "\images//horizonSmall.png",
        name: "Horizon: Zero Dawn II",
        imageLarge: "\images//horizonLarge.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 6 minutes ago",
        checkpointImage: "\images//horizonCheckPoint.png",
        checkpointName: "The Banuk Mystery ",
        date: "12/24",
        time: "04:15 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Banku Legend",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Chasing Heights",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 4,
        image: "\images//assassinsCreedSmall.png",
        name: "Assassins Creed: Valhalla",
        imageLarge: "\images//sekiroLarge.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 6 minutes ago",
        checkpointImage: "\images//horizonCheckPoint.png",
        checkpointName: "The Banuk Mystery ",
        date: "12/24",
        time: "04:15 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Banku Legend",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Chasing Heights",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 5,
        image: "\images//fifaSmall.png",
        name: "Fifa 20",
        imageLarge: "\images//rdrBig.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 6 minutes ago",
        checkpointImage: "\images//horizonCheckPoint.png",
        checkpointName: "The Banuk Mystery ",
        date: "12/24",
        time: "04:15 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Banku Legend",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Chasing Heights",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 6,
        image: "\images//apexSmall.png",
        name: "Apex Legends: Full of Sweats",
        imageLarge: "\images//horizonLarge.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 6 minutes ago",
        checkpointImage: "\images//horizonCheckPoint.png",
        checkpointName: "The Banuk Mystery ",
        date: "12/24",
        time: "04:15 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Banku Legend",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Chasing Heights",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 7,
        image: "\images//gowSmall.png",
        name: "God of War: Game of the Year 2019",
        imageLarge: "\images//sekiroLarge.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 6 minutes ago",
        checkpointImage: "\images//horizonCheckPoint.png",
        checkpointName: "The Banuk Mystery ",
        date: "12/24",
        time: "04:15 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Banku Legend",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Chasing Heights",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
    {
        id: 8,
        image: "\images//game7.png",
        name: "Mortal Kombat",
        imageLarge: "\images//rdrBig.png",
        psLogo: "\images//logowhite.png",
        lastPlayed: "Last played 6 minutes ago",
        checkpointImage: "\images//horizonCheckPoint.png",
        checkpointName: "The Banuk Mystery ",
        date: "12/24",
        time: "04:15 PM",
        achievementImageOne: "\images//sekiroAchievementOne.png",
        achievementNameOne: "Banku Legend",
        sliverTrophyImage:"\images/silverTrophy.png",
        rarityCommonImage: "\images//commTier.png",
        rarityCommon: "Common -35%",
        achievementImageTwo: "\images//sekiroAchievementTwo.png",
        achievementNameTwo: "Chasing Heights",
        goldTrophyImage:"\images//goldtrophy.png",
        rarityRare: "Very Rare - 11.4%",
        rarityRareImage: "\images//veryRareTier.png",

    },
]